--- 
phases: 
  build: 
    commands: 
      - "echo Build started on `date`"
      - "echo Building the Docker image..."
      - "ls"
      - "docker build -t vickyrv2206/nginx ."
      - "docker tag vickyrv2206/nginx vickyrv2206/nginx:latest"
  post_build: 
    commands: 
      - "echo Build completed on `date`"
      - "echo Pushing the Docker image..."
      - "docker push vickyrv2206/nginx:latest"
  pre_build: 
    commands: 
      - "echo Logging in to Docker Hub..."
      - "docker login --username=\"vickyrv2206\" --password=\"Yathuviki@0611\""
version: 0.1
